apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: payment
  labels:
    app.kubernetes.io/name: payment
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: payment
        app.kubernetes.io/version: 1.0-SNAPSHOT
      namespace: user2-cloudnativeapps
    spec:
      containerConcurrency: 0
      containers:
        - image: ghcr.io/rhsgsa/payment-native:1.0-SNAPSHOT
          name: payment
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers:
  - my-cluster-kafka-bootstrap.demo:9092
  topics:
  - orders
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: payment
