apiVersion: v1
kind: Service
metadata:
  labels:
    app: cart
    app.kubernetes.io/name: cart
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: cart
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: cart
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '["example-infinispan","my-cluster"]'
  labels:
    app: cart
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/name: cart
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/part-of: cart
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cart
        app.kubernetes.io/version: 1.0-SNAPSHOT
        app.kubernetes.io/name: cart
        app.openshift.io/runtime: quarkus
    spec:
      containers:
      - image: ghcr.io/rhsgsa/cart:1.0-SNAPSHOT
        name: cart
        env:
        - name: QUARKUS_INFINISPAN_CLIENT_SERVER_LIST
          value: example-infinispan:11222
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 500Mi
status: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cart
    app.kubernetes.io/name: cart
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: cart
spec:
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  to:
    kind: Service
    name: cart
---
