apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kafka
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        values:
          namespace: demo
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "20"
      name: "{{cluster}}-kafka"
    spec:
      destination:
        namespace: "{{values.namespace}}"
        name: "{{cluster}}"
      project: default
      source:
        kustomize: {}
        path: kafka/base
        repoURL: http://gitea.infra.svc.cluster.local:3000/demo/coolstore.git
        targetRevision: HEAD
      syncPolicy:
        automated: {}
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
      ignoreDifferences:
      - group: kafka.strimzi.io
        kind: KafkaTopic
        jqPathExpressions:
        - '.metadata.labels.app."app.kubernetes.io/instance"'
        - .spec.config
        - .spec.partitions