apiVersion: v1
kind: Namespace
metadata:
  name: data-grid-operator
spec: {}
status: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: datagrid
  namespace: data-grid-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: datagrid-operator
  namespace: data-grid-operator
spec:
  channel: 8.4.x
  installPlanApproval: Automatic
  name: datagrid
  source: redhat-operators
  sourceNamespace: openshift-marketplace