apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: amq-streams
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - cluster: coolstore-a
        values:
          namespace: amq-streams-operator
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "10"
      name: "{{cluster}}-amq-streams"
    spec:
      destination:
        namespace: "{{values.namespace}}"
        name: "{{cluster}}"
      project: default
      source:
        directory: {}
        path: amq-streams
        repoURL: http://gitea.infra.svc.cluster.local:3000/demo/coolstore.git
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated: {}
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100