apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          kafka: "true"
      values:
        namespace: demo
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "50"
      name: "{{name}}-monitoring"
    spec:
      destination:
        namespace: "{{values.namespace}}"
        name: "{{name}}"
      project: default
      source:
        directory:
          jsonnet: {}
          recurse: true
        path: monitoring
        repoURL: http://gitea.infra.svc.cluster.local:3000/demo/coolstore.git
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
        - RespectIgnoreDifferences=true
        automated: {}
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
