apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: order-secondary
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - cluster: coolstore-b
        values:
          namespace: demo
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "30"
      name: "{{cluster}}-order-secondary"
    spec:
      destination:
        namespace: "{{values.namespace}}"
        name: "{{cluster}}"
      project: default
      source:
        kustomize: {}
        path: services/order/app/overlays/secondary
        repoURL: http://gitea.infra.svc.cluster.local:3000/demo/coolstore.git
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        automated: {}
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 100
