apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: order
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: order-artifact-image
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: order
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: order-artifact-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: order-artifact-image:1.0-SNAPSHOT
  postCommit: {}
  resources: {}
  source:
    contextDir: m4/order-service
    git:
      uri: https://github.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2-labs-solutions.git
      ref: ocp-4.10
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      env:
      #- name: MAVEN_MIRROR_URL
      #  value: http://nexus:8081/repository/maven-all-public/
      - name: MAVEN_ARGS
        value: "compile package -DskipTests -Dquarkus.kubernetes.deploy=false"
      - name: ARTIFACT_COPY_ARGS
        value: "-r quarkus-app/"
      from:
        kind: ImageStreamTag
        name: ubi8-openjdk-11:1.10
        namespace: openshift
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChange: {}
status:
  lastVersion: 0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: order
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: order
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: order
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: openjdk-11
spec:
  dockerImageRepository: registry.access.redhat.com/ubi8/openjdk-11
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: order
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: order
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name: order
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: order
spec:
  output:
    to:
      kind: ImageStreamTag
      name: order:1.0-SNAPSHOT
  source:
    dockerfile: "####\n# This Dockerfile is used in order to build a container that\
      \ runs the Quarkus application in JVM mode\n#\n# Before building the container\
      \ image run:\n#\n# ./mvnw package\n#\n# Then, build the image with:\n#\n# docker\
      \ build -f src/main/docker/Dockerfile.jvm -t quarkus/code-with-quarkus-jvm .\n\
      #\n# Then run the container using:\n#\n# docker run -i --rm -p 8080:8080 quarkus/code-with-quarkus-jvm\n\
      #\n# If you want to include the debug port into your docker image\n# you will\
      \ have to expose the debug port (default 5005) like this :  EXPOSE 8080 5005\n\
      #\n# Then run the container using :\n#\n# docker run -i --rm -p 8080:8080 -p\
      \ 5005:5005 -e JAVA_ENABLE_DEBUG=\"true\" quarkus/code-with-quarkus-jvm\n#\n\
      ###\nFROM registry.access.redhat.com/ubi8/ubi-minimal:8.4 \n\nARG JAVA_PACKAGE=java-11-openjdk-headless\n\
      ARG RUN_JAVA_VERSION=1.3.8\nENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'\n# Install\
      \ java and the run-java script\n# Also set up permissions for user `1001`\n\
      RUN microdnf install curl ca-certificates ${JAVA_PACKAGE} \\\n    && microdnf\
      \ update \\\n    && microdnf clean all \\\n    && mkdir /deployments \\\n  \
      \  && chown 1001 /deployments \\\n    && chmod \"g+rwX\" /deployments \\\n \
      \   && chown 1001:root /deployments \\\n    && curl https://repo1.maven.org/maven2/io/fabric8/run-java-sh/${RUN_JAVA_VERSION}/run-java-sh-${RUN_JAVA_VERSION}-sh.sh\
      \ -o /deployments/run-java.sh \\\n    && chown 1001 /deployments/run-java.sh\
      \ \\\n    && chmod 540 /deployments/run-java.sh \\\n    && echo \"securerandom.source=file:/dev/urandom\"\
      \ >> /etc/alternatives/jre/conf/security/java.security\n\n# Configure the JAVA_OPTIONS,\
      \ you can add -XshowSettings:vm to also display the heap size.\nENV JAVA_OPTIONS=\"\
      -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager\"\
      \n# We make four distinct layers so if there are application changes the library\
      \ layers can be re-used\nCOPY --chown=1001 target/quarkus-app/lib/ /deployments/lib/\n\
      COPY --chown=1001 target/quarkus-app/*.jar /deployments/\nCOPY --chown=1001\
      \ target/quarkus-app/app/ /deployments/app/\nCOPY --chown=1001 target/quarkus-app/quarkus/\
      \ /deployments/quarkus/\n\nEXPOSE 8080\nUSER 1001\n\nENTRYPOINT [ \"/deployments/run-java.sh\"\
      \ ]\n\n"
    images:
    - from:
        kind: ImageStreamTag
        name: order-artifact-image:1.0-SNAPSHOT
      paths:
      - sourcePath: "/deployments/."
        destinationDir: "./target/"
  strategy:
    dockerStrategy: {}
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChange:
      from:
        kind: ImageStreamTag
        name: order-artifact-image:1.0-SNAPSHOT
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/connects-to: my-cluster,order-database
  labels:
    app.kubernetes.io/name: order
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/part-of: order
  name: order
spec:
  replicas: 1
  selector:
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/name: order
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order
        app.kubernetes.io/version: 1.0-SNAPSHOT
        app.openshift.io/runtime: quarkus
    spec:
      containers:
        - env:
            - name: QUARKUS_MONGODB_DATABASE
              value: orders
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: ""
          imagePullPolicy: IfNotPresent
          name: order
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - order
        from:
          kind: ImageStreamTag
          name: order:1.0-SNAPSHOT
      type: ImageChange
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: order
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: order
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: order
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: order-database
    app.kubernetes.io/component: order-database
    app.kubernetes.io/instance: order-database
  name: order-database
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/openshiftlabs/ccn-mongo:4.0
    from:
      kind: DockerImage
      name: quay.io/openshiftlabs/ccn-mongo:4.0
    generation: null
    importPolicy: {}
    name: "4.0"
    referencePolicy:
      type: "Source"
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: order-database
    app.kubernetes.io/component: order-database
    app.kubernetes.io/instance: order-database
    app.kubernetes.io/part-of: order
    app.openshift.io/runtime: mongodb
  name: order-database
spec:
  replicas: 1
  selector:
    deploymentconfig: order-database
  strategy:
    resources: {}
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deploymentconfig: order-database
    spec:
      containers:
      - image: quay.io/openshiftlabs/ccn-mongo:4.0
        name: order-database
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /data/configdb
          name: order-database-volume-1
        - mountPath: /data/db
          name: order-database-volume-2
      volumes:
      - emptyDir: {}
        name: order-database-volume-1
      - emptyDir: {}
        name: order-database-volume-2
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - order-database
      from:
        kind: ImageStreamTag
        name: order-database:4.0
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: order-database
    app.kubernetes.io/component: order-database
    app.kubernetes.io/instance: order-database
  name: order-database
spec:
  ports:
  - name: 27017-tcp
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    deploymentconfig: order-database
status:
  loadBalancer: {}
