apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
- xsite-service.yaml

patches:
- patch: |-
    apiVersion: infinispan.org/v1
    kind: Infinispan
    metadata:
      name: example-infinispan
    spec:
      service:
        sites:
          local:
            name: INFINISPAN-C
          locations:
          - name: INFINISPAN-A
            url: infinispan+xsite://infinispan-a.demo.svc.clusterset.local:7900
          - name: INFINISPAN-B
            url: infinispan+xsite://infinispan-b.demo.svc.clusterset.local:7900
- patch: |-
    kind: Cache
    apiVersion: infinispan.org/v2alpha1
    metadata:
      name: cart
    spec:
      template: |
        distributedCache:
          mode: "SYNC"
          # https://infinispan.org/docs/stable/titles/xsite/xsite.html#cross-site-automatic-offline_cross-site-replication
          backups:
            INFINISPAN-A:
              backup:
                strategy: "SYNC"
                timeout: "60000"
            INFINISPAN-B:
              backup:
                strategy: "SYNC"
                timeout: "60000"
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: MP_MESSAGING_OUTGOING_ORDERS_BOOTSTRAP_SERVERS
        value: my-cluster-kafka-bootstrap.demo.svc.clusterset.local:9092
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: CART_CLUSTER_NAME
        value: coolstore-c
  target:
    kind: Deployment
    name: cart
