apiVersion: v1
entries:
  amq-streams:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2022-09-20T16:58:59.744872+08:00"
    description: A Helm chart for Kubernetes
    digest: 2dbb2b9cf186e5ecbae4528f39fbb31a8b92aa12acdf56f2fdcda72451ec0123
    name: amq-streams
    type: application
    urls:
    - amq-streams-0.1.0.tgz
    version: 0.1.0
  kafka:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2022-09-20T16:58:59.745061+08:00"
    description: A Helm chart for Kubernetes
    digest: 4dda0cdf035153d4163fcb9662a6e31d5bba6e53b47964a7c1f3d1edd4f2efa4
    name: kafka
    type: application
    urls:
    - kafka-0.1.0.tgz
    version: 0.1.0
  payment:
  - apiVersion: v2
    appVersion: 1.0-SNAPSHOT
    created: "2022-09-20T16:58:59.745244+08:00"
    description: A Helm chart for Kubernetes
    digest: c7f85e308d02c9408f9057d399649ace1340773e072751c61fdb12dc0c2524ff
    name: payment
    type: application
    urls:
    - payment-0.1.0.tgz
    version: 0.1.0
generated: "2022-09-20T16:58:59.744603+08:00"
